### ISSUE TITLE
how is this different from CsgBox3D?

### ISSUE THREAD

**Issue by jasonswearingen** [bikemurt/godot-uv-tools#1]
Hello, I'm pretty new to Godot, so pardon my honest question:  I'm wondering if there is some use I'd get from this different from what I see available in CsgBox3D?  or did you make this tool for an old version?

That said, even if this "isn't needed" anymore, I will study your code as it seems like a good way to understand procedural generation.

Thank you.

**Comment by bikemurt** [comment]
There are a couple of minor differences:
- CSGBox3D doesn't explicitly allow you to set a static or rigidbody
- CSGBox3D would still stretch the UVs upon changing the size unless you use triplanar UV coordinates

I actually started this tool as a way of creating "cube projected" UVs, much in the same way Blender does (see `uv_tools.gd`). Right now it only works on axis-aligned faces, but my original intention was to make it general purpose. Cube projected UVs are like triplanar, but don't require any shader modifications (of course, with the `StandardMaterial3D`, triplanar is just a checkbox).

I made a video about it, and people asked for CSGBox3D like functionality. So that's kind of the history of it.

Another benefit is that it exposes the body, collision shape, and mesh directly in the editor if you need to change anything:
![image](https://github.com/bikemurt/godot-uv-tools/assets/23486102/558b444c-db9f-434a-83a9-877d232770d1)

**Comment by jasonswearingen** [comment]
thank you for the details, very clear.  I will dive in!

**Comment by jasonswearingen** [comment]
fyi, I'm getting towards the point where I could try your repo out.   I'm not a rendering guy, so this AI description of how Triplanar is different from Cube Projected seems to help me understand why to use your tool :)

> Key Differences
> 
>     Blending:
>         Triplanar: Blends the texture based on the surface normal, resulting in smooth transitions between the projections.
>         Cube Projection: Directly applies the texture from the selected face, which can lead to visible seams.
> 
>     Flexibility:
>         Triplanar: More flexible and suitable for complex and curved surfaces due to the dynamic blending.
>         Cube Projection: Best for objects with box-like shapes and less effective for complex shapes.
> 
>     Performance:
>         Triplanar: More computationally expensive due to the blending of three projections.
>         Cube Projection: Less computationally intensive as it involves a direct projection.
> 
> Conclusion
> 
> Choosing between triplanar UV coordinates and cube projected UVs depends on the specific requirements of your project. For complex, curved surfaces where seamless texturing is crucial, triplanar mapping is a better choice. For simpler, boxy shapes where performance is a concern, cube projection is more suitable.
>
